version: '3.8'

services:
  # 1. Database Service
  mongo:
    image: mongo
    container_name: finance_db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  # 2. Backend Service
  api:
    build: ./backend
    container_name: finance_api
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/finance
    depends_on:
      - mongo

  # 3. Frontend Service
  client:
    build: ./frontend
    container_name: finance_client
    ports:
      - "8080:80"
    depends_on:
      - api

volumes:
  mongo-data: