version: '3.8'

services:
  # 1. Database
  mongo:
    image: mongo
    container_name: finance_db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  # 2. Backend (Updated to match your screenshot)
  api:
    image: zaidsmadii/finance-tracker:latest  # <--- WE FIXED THIS NAME
    container_name: finance_api
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/finance
    depends_on:
      - mongo

  # 3. Frontend
  client:
    image: zaidsmadii/finance-frontend:latest
    container_name: finance_client
    ports:
      - "3000:80"
    depends_on:
      - api

volumes:
  mongo-data: